import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Disclaimer - Age Calculator BD',
  description: 'Disclaimer for Age Calculator BD by VHIR Tech. Important information about the accuracy and intended use of our tools.',
  alternates: { canonical: 'https://age.vhirtech.shop/disclaimer' },
};

export default function DisclaimerPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        <section className="py-12 sm:py-16">
          <div className="mx-auto max-w-4xl px-4 sm:px-6">
            <h1 className="mb-8 text-center text-3xl font-extrabold text-white sm:text-4xl">⚠️ Disclaimer</h1>
            <div className="glass-card rounded-2xl p-6 sm:p-8">
              <article className="space-y-6 text-sm leading-relaxed text-slate-300">
                <section>
                  <h2 className="mb-3 text-lg font-bold text-white">General Disclaimer</h2>
                  <p>The information provided by Age Calculator BD (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) on age.vhirtech.shop is for general informational purposes only. All information on the site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the site.</p>
                </section>

                <section>
                  <h2 className="mb-3 text-lg font-bold text-white">Age Calculation Accuracy</h2>
                  <p>Our age calculator uses the Gregorian calendar and standard time calculations. While we strive for maximum accuracy, results may have minor variations due to factors such as leap years, time zones, and daylight saving time. The calculations should be considered approximate for official purposes.</p>
                </section>

                <section>
                  <h2 className="mb-3 text-lg font-bold text-white">Job Quota Information</h2>
                  <p className="mb-2 font-medium text-amber-400">⚠️ IMPORTANT: The BD government job age limits displayed on our website are based on publicly available information and may not reflect the most current regulations. Age limits are subject to change by government policy at any time.</p>
                  <p>Our Job Quota Tracker is provided for informational and educational purposes only. It should <strong>NOT</strong> be used as the sole basis for making career decisions, job applications, or legal determinations. Always verify age limits with official government sources, job circulars, and relevant authorities before applying for any position.</p>
                </section>

                <section>
                  <h2 className="mb-3 text-lg font-bold text-white">Fascinating Facts</h2>
                  <p>The fascinating facts and statistics generated by our tool (such as heartbeats, breaths, distance walked, etc.) are estimates based on average human values and are provided for entertainment and educational purposes only. Individual results may vary significantly based on personal health, lifestyle, and other factors.</p>
                </section>

                <section>
                  <h2 className="mb-3 text-lg font-bold text-white">External Links</h2>
                  <p>Our website may contain links to external websites that are not provided or maintained by us. We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.</p>
                </section>

                <section>
                  <h2 className="mb-3 text-lg font-bold text-white">Professional Advice</h2>
                  <p>The site cannot and does not contain professional advice. The information is provided for general informational and educational purposes only. They are not a substitute for professional advice from qualified professionals.</p>
                </section>

                <section>
                  <h2 className="mb-3 text-lg font-bold text-white">Consent</h2>
                  <p>By using our website, you hereby consent to our Disclaimer and agree to its terms. If you have any questions, please contact us:</p>
                  <a href="mailto:vhirsupport@gmail.com" className="mt-2 inline-flex items-center gap-2 rounded-lg bg-teal-500/10 px-4 py-2 text-sm font-medium text-teal-400 transition-colors hover:bg-teal-500/20">
                    📧 vhirsupport@gmail.com
                  </a>
                </section>
              </article>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
